language: python
dist: xenial

matrix:
  include:
    - python: 3.8
      env: TOX_ENV='lint'
    # Django 2.2
    - python: 3.5
      env: DJANGO='dj22'
    - python: 3.6
      env: DJANGO='dj22'
    - python: 3.7
      env: DJANGO='dj22'
    - python: 3.8
      env: DJANGO='dj22'
    # Django 3.0
    - python: 3.6
      env: DJANGO='dj30'
    - python: 3.7
      env: DJANGO='dj30'
    - python: 3.8
      env: DJANGO='dj30'
    # Django 3.1
    - python: 3.6
      env: DJANGO='dj31'
    - python: 3.7
      env: DJANGO='dj31'
    - python: 3.8
      env: DJANGO='dj31'

install:
  - pip install tox coverage
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
